set_property SRC_FILE_INFO {cfile:/afs/ee.cooper.edu/user/r/ridwan.hussain/testProject2/testProject2.srcs/constrs_1/new/testProject2.xdc rfile:../../../testProject2.srcs/constrs_1/new/testProject2.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W22 IOSTANDARD LVCMOS33} [get_ports D]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W22 IOSTANDARD LVCMOS33} [get_ports D]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P22 [get_ports {C[0]}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N22 [get_ports {B[0]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M22 [get_ports {A[0]}]
