# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/TestConstraint.xdc

# Block Designs: bd/TestProgram/TestProgram.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TestProgram || ORIG_REF_NAME==TestProgram} -quiet] -quiet

# IP: bd/TestProgram/ip/TestProgram_util_vector_logic_0_0/TestProgram_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TestProgram_util_vector_logic_0_0 || ORIG_REF_NAME==TestProgram_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/TestProgram/ip/TestProgram_util_vector_logic_1_0/TestProgram_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TestProgram_util_vector_logic_1_0 || ORIG_REF_NAME==TestProgram_util_vector_logic_1_0} -quiet] -quiet

# XDC: bd/TestProgram/TestProgram_ooc.xdc
