#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Sep 21 20:59:01 EDT 2023
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 18d4d6bd85b64fc58e72f27cba70d384 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot RippleCarryAdder_tb_behav xil_defaultlib.RippleCarryAdder_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto 18d4d6bd85b64fc58e72f27cba70d384 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot RippleCarryAdder_tb_behav xil_defaultlib.RippleCarryAdder_tb xil_defaultlib.glbl -log elaborate.log

